/* Main.c file generated by New Project wizard
 *
 * Created:   qui ago 8 2024
 * Processor: 8086
 * Compiler:  Digital Mars C
 *
 * Before starting simulation set Internal Memory Size 
 * in the 8086 model properties to 0x10000
 */

#define IO0  0000h
#define IO1  0200h
#define IO2  0400h
#define IO3  0600h
#define IO4  0800h
#define IO5  0A00h
#define IO6  0C00h
#define IO7  0E00h
#define IO8  1000h
#define IO9  1200h
#define IO10 1400h
#define IO11 1600h
#define IO12 1800h
#define IO13 1A00h
#define IO14 1C00h
#define IO15 1E00H

unsigned char HORA = 0;
unsigned char MINUTO = 0;

unsigned char tabela_4511[10] = {
    63,  // 0 
    6,   // 1 
    91,  // 2 
    79,  // 3 
    102, // 4 
    109, // 5 
    125, // 6 
    7,   // 7 
    127, // 8 
    111  // 9 
};


void Inicializa_Relogio(void)
{
    HORA = 0;
    MINUTO = 0;
}

void Delay_288(void)
{
    asm 
    {
        mov cx, 54612 
    decrement:
        dec cx 
        cmp cx, 0 
        jne decrement 
    }
}

void Delay(void)
{
    asm {
        call Delay_288
        call Delay_288
        call Delay_288
        call Delay_288
    }
}

void Atualiza_Relogio(void)
{
    asm {
        inc MINUTO
        cmp MINUTO, 60
        je  ZERA_MINUTO
        jmp Sai_Atualiza_Relogio

    ZERA_MINUTO:
        mov MINUTO, 0
        inc HORA
        cmp HORA, 24
        je  ZERA_HORA
        jmp Sai_Atualiza_Relogio

    ZERA_HORA:
        mov HORA, 0
    
    Sai_Atualiza_Relogio:    
    }
}

void Mostra_Relogio(void)
{
    unsigned char hr_dezena, hr_uni;
    unsigned char mn_dezena, mn_unidade;
    unsigned char exibir_num_display;

    asm {
        mov al, HORA      
        mov ah, 0        
        mov bl, 10       
        div bl     
        mov hr_dezena, al 
        mov hr_uni, ah 
    }

    
    asm {
        mov al, MINUTO    
        mov ah, 0        
        mov bl, 10       
        div bl            
        mov mn_dezena, al 
        mov mn_unidade, ah 
    }

    // Mostra as dezenas das horas
    exibir_num_display = tabela_4511[hr_dezena];
    asm {
        mov al, exibir_num_display
        mov dx, IO2
        out dx, al
    }

    // Mostra as unidades das horas
    exibir_num_display = tabela_4511[hr_uni];
    asm {
        mov al, exibir_num_display
        mov dx, IO3
        out dx, al
    }

    // Mostra as dezenas dos minutos
    exibir_num_display = tabela_4511[mn_dezena];
    asm {
        mov al, exibir_num_display
        mov dx, IO4
        out dx, al
    }

    // Mostra as unidades dos minutos
    exibir_num_display = tabela_4511[mn_unidade];
    asm {
        mov al, exibir_num_display
        mov dx, IO5
        out dx, al
    }
}

void main(void)
{
    Inicializa_Relogio();
    Mostra_Relogio();

    while(1)
    {
        asm {
            call Atualiza_Relogio
            call Mostra_Relogio //joga display
            call Delay
        }
    }
}
